name: Automate all the actions
on:
  workflow_dispatch:

jobs:
  docker-build-and-run:
    runs-on: ubuntu-latest
  steps:
    - name: docker build
      run: docker build -t midhunshanmugam/application:gta .
