name: Automate all the actions

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker build
        run: docker build -t midhunshanmugam/application:gta .

      - name: Docker push
        run: docker push midhunshanmugam/application:gta
      
      - name: Run Docker container
        run: docker run -p 5000:5000 --name gta-container midhunshanmugam/application:gta

      - name: Check running container
        run: docker ps